Initial refactoring of the project
stefano-garzarella/vhost-user-vsock pull request #8
Opened 2021-05-28 22:23 UTC by harshanavkis

Split the project into separate files.

2021-06-03 10:57 UTC, stefano-garzarella requested changes
`cargo clippy` complains about `VhostUserResult`

In addition, I think we can remove `vhost_user_vsock_` prefix from each files.
And we can merge def_types, const, and err files in a single file, or even better include them in lib.rs, then we can use Error for example with `use super::Error` in the other files.

2021-06-03 10:57 UTC, stefano-garzarella commented on src/vhost_user_vsock_def_types.rs
> +pub type VhostUserResult<T> = std::result::Result<T, VhostUserError>;
It seems that we never use VhostUserResult:

```bash
$ cargo clippy
warning: type alias is never used: `VhostUserResult`
 --> src/vhost_user_vsock_def_types.rs:4:1
  |
4 | pub type VhostUserResult<T> = std::result::Result<T, VhostUserError>;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(dead_code)]` on by default

warning: 1 warning emitted

    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
```

2021-06-10 20:32 UTC, harshanavkis commented
@stefano-garzarella I have made the requested changes. However, clippy does not complain now about the unused type alias.

2021-06-11 07:51 UTC, stefano-garzarella commented
@harshanavkis thanks!
This PR LGTM!

Just a couple of suggestions for next steps:

1. I suggest to fix your git author setup with "Name Surname", since most of upstream projects requires it. For this repository is fine, since for now it is only a PoC, but when we will push on rust-vmm crates, kata, etc. they may have this requirement. For example the Linux kernel doc explains it very well [here](https://www.kernel.org/doc/html/v4.17/process/submitting-patches.html#sign-your-work-the-developer-s-certificate-of-origin)
2. `VhostUserResult` seems really unused, so I think we can clean a bit removing it in next patches/PRs

2021-06-11 07:52 UTC, stefano-garzarella approved these changes

2021-06-11 07:52 UTC, merged